import * as THREE from './three.module.min.js';

const canvas=document.getElementById('town3d'),wrap=document.getElementById('mapwrap');
if(!canvas||!wrap)throw new Error('Hush 3D surface missing');
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(32,1,.1,100),lookAt=new THREE.Vector3(0,2.45,0);
camera.position.set(0,5.25,18);camera.lookAt(lookAt);const cameraDir=camera.position.clone().sub(lookAt).normalize(),defaultZoom=camera.position.distanceTo(lookAt);let zoomDistance=defaultZoom,zoomNow=zoomDistance;
new THREE.TextureLoader().load('./assets/day-bg.png',t=>{t.colorSpace=THREE.SRGBColorSpace;const bg=new THREE.Mesh(new THREE.PlaneGeometry(72,40.5),new THREE.MeshBasicMaterial({map:t,depthWrite:false}));bg.position.copy(lookAt).addScaledVector(cameraDir,-28);bg.lookAt(camera.position);bg.renderOrder=-10;scene.add(bg);});
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;
scene.add(new THREE.HemisphereLight(0xc8efff,0x766044,2.3));const sun=new THREE.DirectionalLight(0xffd9a3,3.3);sun.position.set(-7,12,8);sun.castShadow=true;scene.add(sun);
const root=new THREE.Group();scene.add(root);const hit=[],falling=[];
const material=(color,opt={})=>new THREE.MeshStandardMaterial({color,roughness:.76,...opt});
const wood=material(0x9b512e),dark=material(0x4b2b27),wall=material(0xf0ddb4),roof=material(0x46323b),stone=material(0x73747b),green=material(0x568e39),lime=material(0x78b64a),paper=material(0xf3dfb5),brass=material(0xc68a35,{metalness:.35}),glow=material(0xffc566,{emissive:0xff9f32,emissiveIntensity:1.15});
function make(g,m,p){const o=new THREE.Mesh(g,m);o.position.set(...p);o.castShadow=o.receiveShadow=true;return o}function box(s,m,p){return make(new THREE.BoxGeometry(...s),m,p)}function act(o,a){o.userData.action=a;hit.push(o);return o}
root.add(make(new THREE.CylinderGeometry(8,8.5,.65,10),material(0x79a655),[0,-.35,0]));
const path=make(new THREE.RingGeometry(3.6,5,48,1,0,Math.PI*1.45),material(0xa8a09a),[0,.01,0]);path.rotation.x=-Math.PI/2;path.rotation.z=.5;root.add(path);
const inn=new THREE.Group();root.add(inn);inn.add(box([5,2.35,4.8],wall,[0,1.2,0]),box([4.65,2,4.5],wall,[0,3.15,0]));
function closeGables(){const s=new THREE.Shape();s.moveTo(-2.48,4.08);s.lineTo(2.48,4.08);s.lineTo(0,5.78);s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:.20,bevelEnabled:false});const front=make(g,wall,[0,0,2.36]);front.castShadow=front.receiveShadow=true;inn.add(front);const back=make(g,wall,[0,0,-2.56]);back.castShadow=back.receiveShadow=true;inn.add(back)}closeGables();
[-2.25,0,2.25].forEach(x=>inn.add(box([.22,4.4,4.95],wood,[x,2.25,0])));[.15,2.35,4.2].forEach(y=>inn.add(box([5.2,.22,4.95],wood,[0,y,0])));
[-1.3,1.3].forEach(x=>{const r=box([3.1,.3,5.4],roof,[x,4.95,0]);r.rotation.z=x<0?.58:-.58;inn.add(r)});inn.add(box([.75,1.8,.75],stone,[1.4,5.1,-.7]));
/* layered roof tiles, ridge cap, half-timber façade and framed windows */
for(const side of [-1,1])for(let row=0;row<4;row++)for(let z=-2.25;z<=2.25;z+=.52){const x=side*(.38+row*.62),y=5.52-row*.42;const tile=box([.72,.09,.48],roof,[x,y,z]);tile.rotation.z=side<0?.58:-.58;inn.add(tile)}
inn.add(box([.30,.30,5.72],roof,[0,5.78,0]));
function frontBeam(x,y,len,rot=0,w=.14){const b=box([w,len,.14],wood,[x,y,2.53]);b.rotation.z=rot;inn.add(b)}
[-1.72,0,1.72].forEach(x=>frontBeam(x,2.25,4.05));frontBeam(-1.05,3.25,2.2,-.62);frontBeam(1.05,3.25,2.2,.62);frontBeam(-1.05,1.25,2.05,.55);frontBeam(1.1,1.25,2.05,-.55);
frontBeam(0,4.88,1.38,0,.13);frontBeam(-.70,4.76,1.70,-.72,.13);frontBeam(.70,4.76,1.70,.72,.13);
function windowFrame(x,y){inn.add(box([1.03,1.08,.18],dark,[x,y,2.55]));inn.add(box([.78,.84,.20],glow,[x,y,2.66]));inn.add(box([.08,.88,.22],dark,[x,y,2.78]),box([.82,.08,.22],dark,[x,y,2.78]));}
[[-1.55,1.35],[1.55,1.35],[0,3.25]].forEach(v=>windowFrame(...v));
function planter(x){inn.add(box([1.18,.38,.42],wood,[x,.78,2.82]));for(let i=-2;i<=2;i++){inn.add(make(new THREE.SphereGeometry(.11,10,7),i%2?material(0xf06f72):material(0xffb0a4),[x+i*.19,1.06+Math.abs(i%2)*.08,2.86]));inn.add(make(new THREE.TetrahedronGeometry(.12),green,[x+i*.18,.96,2.83]));}}planter(-1.55);planter(1.55);
const doorPivot=new THREE.Group();doorPivot.position.set(-.7,.15,2.46);inn.add(doorPivot);doorPivot.add(act(box([1.4,2.2,.18],dark,[.7,1.1,0]),'door'));doorPivot.add(make(new THREE.SphereGeometry(.09,12,8),brass,[1.2,1.05,.13]));
const tree=new THREE.Group();tree.position.set(-4.5,0,1.3);root.add(tree);tree.add(act(make(new THREE.CylinderGeometry(.48,.75,3.8,7),wood,[0,1.9,0]),'tree'));const crowns=[];
[[0,4.2,0,1.5],[-1.05,3.85,.15,1.15],[1.05,3.9,.1,1.2],[-.55,4.65,-.4,1.05],[.65,4.75,-.35,1.1]].forEach((v,i)=>{const c=act(make(new THREE.DodecahedronGeometry(v[3],1),i%2?green:lime,[v[0],v[1],v[2]]),'tree');c.userData.y=v[1];tree.add(c);crowns.push(c)});
function leaves(){for(let i=0;i<22;i++){const l=make(new THREE.TetrahedronGeometry(.09),i%2?green:lime,[tree.position.x+(Math.random()-.5)*3.2,4.8+Math.random(),tree.position.z+(Math.random()-.5)*2],false);l.userData.v=.012+Math.random()*.02;scene.add(l);falling.push(l)}}
const mail=new THREE.Group();mail.position.set(3.65,0,2.3);root.add(mail);mail.add(box([.32,1.55,.32],wood,[0,.78,0]),act(box([1.25,1.05,1],wood,[0,1.75,0]),'mailbox'));const lidPivot=new THREE.Group();lidPivot.position.set(0,2.3,-.48);mail.add(lidPivot);lidPivot.add(act(box([1.45,.18,1.18],roof,[0,0,.52]),'mailbox'));const letter=box([.75,.06,.5],paper,[0,1.83,0]);letter.visible=false;mail.add(letter);
/* café furniture sits on the front terrace (positive Z = camera-facing side) */
function tableAt(x){const table=new THREE.Group();table.position.set(x,0,3.55);root.add(table);for(let s=-.65;s<=.65;s+=.43)table.add(box([.34,.18,1.05],wood,[s,1.02,0]));[-.65,.65].forEach(px=>[-.34,.34].forEach(z=>table.add(box([.16,1,.16],wood,[px,.5,z]))));return table}tableAt(-2.35);tableAt(2.35);
function chairAt(x,z,turn=0){const c=new THREE.Group();c.position.set(x,0,z);c.rotation.y=turn;root.add(c);c.add(box([.82,.15,.78],wood,[0,.72,0]));[-.31,.31].forEach(px=>[-.28,.28].forEach(pz=>c.add(box([.13,.72,.13],wood,[px,.36,pz]))));c.add(box([.82,.14,.14],wood,[0,1.45,-.32]));[-.32,.32].forEach(px=>c.add(box([.13,.78,.13],wood,[px,1.08,-.32])));return c}
chairAt(-3.55,3.55,-Math.PI/2);chairAt(-1.15,3.55,Math.PI/2);chairAt(1.15,3.55,-Math.PI/2);chairAt(3.55,3.55,Math.PI/2);
function cupAt(x){const c=act(make(new THREE.CylinderGeometry(.22,.19,.34,16),paper,[x,1.30,3.55]),'cup');root.add(c);root.add(make(new THREE.CylinderGeometry(.175,.175,.012,16),material(0x5b2f20),[x,1.477,3.55]));const h=make(new THREE.TorusGeometry(.14,.035,7,14,Math.PI*1.5),paper,[x+.23,1.33,3.55]);h.rotation.y=Math.PI/2;root.add(h)}cupAt(-2.35);cupAt(2.35);
let door=false,mailOpen=false,shake=0,target=0;
function trigger(a){canvas.dataset.lastAction=a;if(a==='tree'){shake=performance.now()+1200;leaves();window.townWhisper?.('The old tree shakes awake. Leaves drift into the morning.')}if(a==='mailbox'){mailOpen=!mailOpen;letter.visible=mailOpen;window.townWhisper?.(mailOpen?'A letter from last night is waiting.':'The letter box closes softly.')}if(a==='door'){door=!door;window.townWhisper?.('The inn door opens.');if(door)setTimeout(()=>window.go?.('morning'),900)}if(a==='cup')window.townWhisper?.('The tea is still warm.')}
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let start=0,last=0,drag=false,pressed=false;
function setZoom(f){zoomDistance=Math.max(8.4,Math.min(25,zoomDistance*f));canvas.dataset.zoom=zoomDistance.toFixed(2)}window.townCameraZoom=setZoom;window.townCameraReset=()=>{target=0;zoomDistance=defaultZoom;};
function begin(x){pressed=true;start=last=x;drag=false}function move(x){if(!pressed)return;const d=x-last;if(Math.abs(x-start)>5)drag=true;target+=d*.008;last=x}function end(x,y){if(!pressed)return;pressed=false;if(drag)return;const r=canvas.getBoundingClientRect();pointer.set((x-r.left)/r.width*2-1,-((y-r.top)/r.height)*2+1);ray.setFromCamera(pointer,camera);const h=ray.intersectObjects(hit,false)[0];if(h)trigger(h.object.userData.action)}
canvas.addEventListener('mousedown',e=>{e.stopPropagation();begin(e.clientX)});canvas.addEventListener('mousemove',e=>{e.stopPropagation();move(e.clientX)});canvas.addEventListener('mouseup',e=>{e.stopPropagation();end(e.clientX,e.clientY)});canvas.addEventListener('mouseleave',()=>{pressed=false});
canvas.addEventListener('touchstart',e=>{e.stopPropagation();const p=e.touches[0];begin(p.clientX)},{passive:true});canvas.addEventListener('touchmove',e=>{e.stopPropagation();move(e.touches[0].clientX)},{passive:true});canvas.addEventListener('touchend',e=>{e.stopPropagation();const p=e.changedTouches[0];end(p.clientX,p.clientY)},{passive:true});
let pinch=0;canvas.addEventListener('touchstart',e=>{if(e.touches.length===2){pressed=false;pinch=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY)}},{passive:true});canvas.addEventListener('touchmove',e=>{if(e.touches.length===2&&pinch){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);setZoom(pinch/d);pinch=d;}},{passive:true});canvas.addEventListener('wheel',e=>{e.preventDefault();setZoom(e.deltaY>0?1.08:.92)},{passive:false});
function resize(){const r=wrap.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(wrap);resize();
function loop(t){requestAnimationFrame(loop);zoomNow+=(zoomDistance-zoomNow)*.12;camera.position.copy(lookAt).addScaledVector(cameraDir,zoomNow);camera.lookAt(lookAt);root.rotation.y+=(target-root.rotation.y)*.08;canvas.dataset.rotation=root.rotation.y.toFixed(3);crowns.forEach((c,i)=>{c.rotation.z=t<shake?Math.sin(t*.025+i)*.12:Math.sin(t*.001+i)*.018;c.position.y=c.userData.y+Math.sin(t*.0012+i)*.04});lidPivot.rotation.x+=((mailOpen?-1.25:0)-lidPivot.rotation.x)*.12;if(mailOpen)letter.position.y+=(2.85-letter.position.y)*.07;else letter.position.y=1.83;doorPivot.rotation.y+=((door?-1.25:0)-doorPivot.rotation.y)*.1;for(let i=falling.length-1;i>=0;i--){const l=falling[i];l.position.y-=l.userData.v;l.rotation.x+=.04;if(l.position.y<.1){scene.remove(l);falling.splice(i,1)}}renderer.render(scene,camera)}
wrap.classList.add('three-ready');canvas.dataset.assets='day-bg, inn-day, tree-turnaround, mailbox-turnaround';requestAnimationFrame(loop);
