import * as THREE from './three.module.min.js';

const canvas=document.getElementById('night3d');
if(canvas){
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(32,1,.1,100),renderer=new THREE.WebGLRenderer({canvas,antialias:true}),lookAt=new THREE.Vector3(0,2.45,0);
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;
camera.position.set(0,5.15,18.5);camera.lookAt(lookAt);const cameraDir=camera.position.clone().sub(lookAt).normalize();
new THREE.TextureLoader().load('./assets/night-bg.png',t=>{t.colorSpace=THREE.SRGBColorSpace;const bg=new THREE.Mesh(new THREE.PlaneGeometry(72,40.5),new THREE.MeshBasicMaterial({map:t,depthWrite:false}));bg.position.copy(lookAt).addScaledVector(cameraDir,-28);bg.lookAt(camera.position);bg.renderOrder=-10;scene.add(bg);});
scene.add(new THREE.HemisphereLight(0x7899d4,0x26160f,1.2));const moon=new THREE.DirectionalLight(0x9bbcff,2.2);moon.position.set(-7,10,6);scene.add(moon);const warm=new THREE.PointLight(0xff9c45,32,16);warm.position.set(0,3.2,4);scene.add(warm);
const root=new THREE.Group();scene.add(root);const hit=[],leaves=[];const mat=(c,o={})=>new THREE.MeshStandardMaterial({color:c,roughness:.78,...o});const wood=mat(0x713921),beam=mat(0x3c211d),wall=mat(0xbca98e),roof=mat(0x161b32),green=mat(0x244c35),gold=mat(0xd79b45,{metalness:.3}),glow=mat(0xffb650,{emissive:0xff7b23,emissiveIntensity:2});
function mesh(g,m,p){const o=new THREE.Mesh(g,m);o.position.set(...p);o.castShadow=o.receiveShadow=true;return o}const box=(s,m,p)=>mesh(new THREE.BoxGeometry(...s),m,p);function active(o,a){o.userData.action=a;hit.push(o);return o}
root.add(mesh(new THREE.CylinderGeometry(8.3,8.8,.55,10),mat(0x263d32),[0,-.3,0]));
const inn=new THREE.Group();root.add(inn);inn.add(box([5.2,4.1,4.7],wall,[0,2.05,0]));[-2.35,0,2.35].forEach(x=>inn.add(box([.23,4.3,4.9],wood,[x,2.15,0])));[.2,2.2,4.1].forEach(y=>inn.add(box([5.35,.23,4.9],wood,[0,y,0])));[-1.35,1.35].forEach(x=>{const r=box([3.2,.34,5.25],roof,[x,4.9,0]);r.rotation.z=x<0?.58:-.58;inn.add(r)});
function closeGables(){const s=new THREE.Shape();s.moveTo(-2.55,4.08);s.lineTo(2.55,4.08);s.lineTo(0,5.75);s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:.20,bevelEnabled:false});const front=mesh(g,wall,[0,0,2.32]);front.castShadow=front.receiveShadow=true;inn.add(front);const back=mesh(g,wall,[0,0,-2.52]);back.castShadow=back.receiveShadow=true;inn.add(back)}closeGables();
for(const side of [-1,1])for(let row=0;row<4;row++)for(let z=-2.25;z<=2.25;z+=.52){const x=side*(.38+row*.62),y=5.49-row*.42;const tile=box([.72,.09,.48],roof,[x,y,z]);tile.rotation.z=side<0?.58:-.58;inn.add(tile)}inn.add(box([.30,.30,5.72],roof,[0,5.75,0]));
function frontBeam(x,y,len,rot=0,w=.14){const b=box([w,len,.14],wood,[x,y,2.49]);b.rotation.z=rot;inn.add(b)}[-1.72,1.72].forEach(x=>frontBeam(x,2.25,4.05));frontBeam(-1.05,3.25,2.2,-.62);frontBeam(1.05,3.25,2.2,.62);frontBeam(-1.05,1.25,2.05,.55);frontBeam(1.1,1.25,2.05,-.55);
frontBeam(0,4.86,1.36,0,.13);frontBeam(-.70,4.74,1.68,-.72,.13);frontBeam(.70,4.74,1.68,.72,.13);
function windowFrame(x,y){inn.add(box([1.03,1.08,.18],beam,[x,y,2.51]));inn.add(active(box([.78,.84,.20],glow,[x,y,2.62]),'window'));inn.add(box([.08,.88,.22],beam,[x,y,2.74]),box([.82,.08,.22],beam,[x,y,2.74]));}[[-1.55,1.35],[1.55,1.35],[0,3.25]].forEach(v=>windowFrame(...v));
function planter(x){inn.add(box([1.18,.38,.42],wood,[x,.78,2.78]));for(let i=-2;i<=2;i++){inn.add(mesh(new THREE.SphereGeometry(.11,10,7),i%2?mat(0xbd4652):mat(0xe98486),[x+i*.19,1.06+Math.abs(i%2)*.08,2.82]));inn.add(mesh(new THREE.TetrahedronGeometry(.12),green,[x+i*.18,.96,2.79]));}}planter(-1.55);planter(1.55);
const doorP=new THREE.Group();doorP.position.set(-.65,.15,2.43);inn.add(doorP);doorP.add(active(box([1.35,2.15,.2],beam,[.68,1.08,0]),'door'));doorP.add(mesh(new THREE.SphereGeometry(.08),gold,[1.14,1.05,.14]));
const tree=new THREE.Group();tree.position.set(-4.4,0,.8);root.add(tree);tree.add(active(mesh(new THREE.CylinderGeometry(.45,.72,3.7,7),wood,[0,1.85,0]),'tree'));const crowns=[];[[0,4.1,0,1.45],[-1,3.8,0,1.1],[1,3.85,0,1.15],[-.4,4.65,-.2,1]].forEach(v=>{const c=active(mesh(new THREE.DodecahedronGeometry(v[3],1),green,[v[0],v[1],v[2]]),'tree');tree.add(c);crowns.push(c)});
const mail=new THREE.Group();mail.position.set(3.7,0,2.2);root.add(mail);mail.add(box([.3,1.5,.3],wood,[0,.75,0]));const mailTop=active(box([1.2,1,1],wood,[0,1.72,0]),'mailbox');mail.add(mailTop);const letter=box([.72,.05,.48],mat(0xf0d6a7),[0,1.8,0]);letter.visible=false;mail.add(letter);
const lantern=new THREE.Group();lantern.position.set(3.8,0,-2.4);root.add(lantern);lantern.add(box([.14,2.4,.14],beam,[0,1.2,0]),active(mesh(new THREE.SphereGeometry(.22,12,8),glow,[0,2.55,0]),'lantern'));
/* the same café terrace remains tangible at night */
function tableAt(x){const table=new THREE.Group();table.position.set(x,0,3.55);root.add(table);for(let s=-.65;s<=.65;s+=.43)table.add(box([.34,.18,1.05],wood,[s,1.02,0]));[-.65,.65].forEach(px=>[-.34,.34].forEach(z=>table.add(box([.16,1,.16],wood,[px,.5,z]))));return table}tableAt(-2.35);tableAt(2.35);
function chairAt(x,z,turn=0){const c=new THREE.Group();c.position.set(x,0,z);c.rotation.y=turn;root.add(c);c.add(box([.82,.15,.78],wood,[0,.72,0]));[-.31,.31].forEach(px=>[-.28,.28].forEach(pz=>c.add(box([.13,.72,.13],wood,[px,.36,pz]))));c.add(box([.82,.14,.14],wood,[0,1.45,-.32]));[-.32,.32].forEach(px=>c.add(box([.13,.78,.13],wood,[px,1.08,-.32])));return c}
chairAt(-3.55,3.55,-Math.PI/2);chairAt(-1.15,3.55,Math.PI/2);chairAt(1.15,3.55,-Math.PI/2);chairAt(3.55,3.55,Math.PI/2);
function cupAt(x){root.add(active(mesh(new THREE.CylinderGeometry(.22,.19,.34,16),wall,[x,1.30,3.55]),'cup'));root.add(mesh(new THREE.CylinderGeometry(.175,.175,.012,16),mat(0x4a251a),[x,1.477,3.55]));const h=mesh(new THREE.TorusGeometry(.14,.035,7,14,Math.PI*1.5),wall,[x+.23,1.33,3.55]);h.rotation.y=Math.PI/2;root.add(h)}cupAt(-2.35);cupAt(2.35);
let drag=false,door=false,mailOpen=false,shake=0;const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();function whisper(t){const el=document.getElementById('hostprompt');if(el)el.textContent=t;window.speak?.(t)}
/* Same controls as the morning room: drag turns the view in place, scroll or pinch walks up the path
   to the door, tapping an object walks up to it first. The sky is a flat painted plane, so the turn
   limits are kept tight enough that its edges never come into frame. */
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,clamp=THREE.MathUtils.clamp,up=new THREE.Vector3(0,1,0);
const far={pos:camera.position.clone(),look:lookAt.clone()},near={pos:new THREE.Vector3(0,2.3,8.2),look:new THREE.Vector3(0,1.7,0)};
const YAW=THREE.MathUtils.degToRad(20),PITCH=THREE.MathUtils.degToRad(6),cur={pos:far.pos.clone(),target:far.look.clone()},pointers=new Map();
let yaw=0,tYaw=0,pitch=0,tPitch=0,walk=0,tWalk=0,tween=null,focused=null,downAt=null,pinch=0;
function freePose(y,p,w){const pos=far.pos.clone().lerp(near.pos,w),dir=far.look.clone().lerp(near.look,w).sub(pos).normalize().applyAxisAngle(up,-y);dir.applyAxisAngle(new THREE.Vector3().crossVectors(dir,up).normalize(),p);return{pos,target:pos.clone().add(dir)}}
function walkTo(to,done){if(reduced){cur.pos.copy(to.pos);cur.target.copy(to.target);done?.();return}tween={from:{pos:cur.pos.clone(),target:cur.target.clone()},to,t0:performance.now(),dur:1000,done}}
function standFor(obj,a){const t=obj.getWorldPosition(new THREE.Vector3()),d=far.pos.clone().sub(t);d.y=0;d.normalize();const pos=t.clone().addScaledVector(d,a==='door'?3.9:3.6);pos.y=t.y+.9;return{pos,target:t}}
function focusOn(obj){if(tween)return;const a=obj.userData.action;focused=a;walkTo(standFor(obj,a),()=>{trigger(a);if(a!=='door')setTimeout(()=>{if(focused===a&&!tween){focused=null;walkTo(freePose(yaw,pitch,walk))}},1800)})}
function walkOut(){if(!focused)return;focused=null;door=false;yaw=tYaw=pitch=tPitch=walk=tWalk=0;walkTo(freePose(0,0,0))}
// Coming back to the door screen later starts from the far view again, door closed.
const section=canvas.closest('section');let wasOn=section?.classList.contains('on');
if(section)new MutationObserver(()=>{const on=section.classList.contains('on');if(on&&!wasOn)walkOut();wasOn=on}).observe(section,{attributes:true,attributeFilter:['class']});
window.nightCameraZoom=f=>{tWalk=clamp(tWalk+(f<1?.15:-.15),0,1)};
function trigger(a){canvas.dataset.lastAction=a;if(a==='tree'){shake=performance.now()+1100;for(let i=0;i<18;i++){const l=mesh(new THREE.TetrahedronGeometry(.08),green,[-4.4+(Math.random()-.5)*3,4+Math.random()*1.5,.8+(Math.random()-.5)*2]);l.userData.v=.012+Math.random()*.018;scene.add(l);leaves.push(l)}whisper('The old tree remembers the wind. Take your time.')}if(a==='mailbox'){mailOpen=!mailOpen;letter.visible=mailOpen;whisper('A sealed thought can wait here until morning.')}if(a==='door'){door=!door;if(localStorage.getItem('hush.setup')){setTimeout(()=>window.openArrivalDoor?.(),420)}else{window.go?.('setup')}}if(a==='window')whisper('Someone left a lamp on for you.');if(a==='lantern'){warm.intensity=warm.intensity>20?8:32;whisper('The lantern lowers its glow.');}if(a==='cup')whisper('The coffee is still warm. Sit for a while.');}
const spread=()=>{const[a,b]=[...pointers.values()];return Math.hypot(a.x-b.x,a.y-b.y)};
const release=e=>{pointers.delete(e.pointerId);if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId)};
canvas.addEventListener('pointerdown',e=>{pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);if(pointers.size===1){downAt={x:e.clientX,y:e.clientY,yaw:tYaw,pitch:tPitch};drag=false}else{downAt=null;drag=true;pinch=spread()}});
canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>=2){if(!tween){const s=spread();tWalk=clamp(tWalk+(s-pinch)*.004,0,1);pinch=s}return}if(!downAt||tween)return;if(Math.hypot(e.clientX-downAt.x,e.clientY-downAt.y)>5)drag=true;tYaw=clamp(downAt.yaw-(e.clientX-downAt.x)*.003,-YAW,YAW);tPitch=clamp(downAt.pitch+(e.clientY-downAt.y)*.003,-PITCH,PITCH)});
canvas.addEventListener('pointerup',e=>{const tap=downAt&&!drag&&pointers.size===1;release(e);downAt=null;if(!tap||tween)return;const r=canvas.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1);ray.setFromCamera(pointer,camera);const h=ray.intersectObjects(hit,false)[0];if(h)focusOn(h.object)});
canvas.addEventListener('pointercancel',e=>{release(e);downAt=null});
canvas.addEventListener('wheel',e=>{e.preventDefault();if(!tween)tWalk=clamp(tWalk-e.deltaY*.0015,0,1)},{passive:false});
canvas.tabIndex=0;canvas.addEventListener('keydown',e=>{if(tween)return;const k=e.key.toLowerCase();if(k==='arrowleft'||k==='a')tYaw=clamp(tYaw-.08,-YAW,YAW);else if(k==='arrowright'||k==='d')tYaw=clamp(tYaw+.08,-YAW,YAW);else if(k==='arrowup'||k==='w')tWalk=clamp(tWalk+.12,0,1);else if(k==='arrowdown'||k==='s')tWalk=clamp(tWalk-.12,0,1);else return;e.preventDefault()});
function resize(){const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(canvas);resize();
function loop(t){requestAnimationFrame(loop);
if(tween){const k=clamp((t-tween.t0)/tween.dur,0,1),e=k<.5?2*k*k:1-Math.pow(-2*k+2,2)/2;cur.pos.lerpVectors(tween.from.pos,tween.to.pos,e);cur.target.lerpVectors(tween.from.target,tween.to.target,e);if(k>=1){const d=tween.done;tween=null;d?.()}}
else if(!focused){yaw+=(tYaw-yaw)*.12;pitch+=(tPitch-pitch)*.12;walk+=(tWalk-walk)*.1;const p=freePose(yaw,pitch,walk);cur.pos.copy(p.pos);cur.target.copy(p.target)}
camera.position.copy(cur.pos);camera.lookAt(cur.target);canvas.dataset.walk=walk.toFixed(2);crowns.forEach((c,i)=>{c.rotation.z=t<shake?Math.sin(t*.025+i)*.13:Math.sin(t*.001+i)*.018});doorP.rotation.y+=((door?-1.15:0)-doorP.rotation.y)*.1;letter.position.y+=((mailOpen?2.72:1.8)-letter.position.y)*.09;for(let i=leaves.length-1;i>=0;i--){leaves[i].position.y-=leaves[i].userData.v;leaves[i].rotation.x+=.04;if(leaves[i].position.y<.1){scene.remove(leaves[i]);leaves.splice(i,1)}}renderer.render(scene,camera)}
canvas.dataset.assets='night-bg, inn-night, inn-interior, tree-turnaround, mailbox-turnaround';requestAnimationFrame(loop);
}
